blank_issues_enabled: false

contact_links:
  - name: 💬 Support Request or Ask a Question
    url: https://forum.syncthing.net/
    about: For general questions or support, please use the Syncthing Community Forum instead of creating an issue here.
