name: "Recycle Runs"

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: lock

jobs:
  recycle-workflow-runs:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run workflow cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          python .github/scripts/recycle-workflow-runs.py
